# Generated by Django 5.2.7 on 2025-10-02 09:44

import tasks.custom_classes
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('creation_date', models.DateField(auto_now=True)),
                ('deadline_date', models.DateField()),
                ('completed_date', models.DateField()),
                ('status', models.CharField(choices=tasks.custom_classes.TaskStatus.get_status_choices, max_length=15)),
                ('priority', models.CharField(choices=tasks.custom_classes.TaskPriority.get_priority_choices, max_length=10)),
            ],
        ),
    ]
