# Generated by Django 5.2.7 on 2025-10-02 10:28

import tasks.custom_classes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_completed_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=tasks.custom_classes.TaskPriority.get_priority_choices, max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.PositiveSmallIntegerField(choices=tasks.custom_classes.TaskStatus.get_status_choices, max_length=15),
        ),
    ]
