# Generated by Django 5.2.7 on 2025-10-02 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_priority_alter_task_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15)),
                ('level', models.PositiveSmallIntegerField()),
                ('color', models.IntegerField()),
                ('description', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15)),
                ('classification', models.PositiveSmallIntegerField()),
                ('flow_order', models.IntegerField()),
                ('is_editable', models.BooleanField()),
                ('color', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.priority'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.status'),
        ),
    ]
