# Generated by Django 5.2.7 on 2025-10-02 13:53

import tasks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_priority_status_alter_task_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='classification',
            field=models.PositiveSmallIntegerField(choices=tasks.models.Classification.get_choices),
        ),
    ]
